let name = "Shawn Lee";
let country = "China";
let is_married = false;
console.log(`${name} was born in ${country}`, is_married);
console.log("This was written in Pino and transpiled to both JavaScript and Python!");
name = readln("What is your name? ");
country = readln("What country were you born in? ");
console.log(`${name} was born in ${country}`);
const arr_int = [];
for (let it = 0; it < 6; it++) arr_int[it] = it + 3;
console.log(arr_int);
